<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RootNamespace>MarkdigWpfViewer</RootNamespace>
	</PropertyGroup>

	<!-- Package -->
	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>Markdig.Wpf.Viewer</PackageId>
		<Version>0.4.0</Version>
		<AssemblyVersion>0.4.0.0</AssemblyVersion>
		<FileVersion>0.4.0.0</FileVersion>
		<InformationalVersion>0.4.0</InformationalVersion>
		<Authors>Porohkun</Authors>
		<Description>Markdown viewer for WPF based on Markdig.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/porohkun/Markdig.Wpf.Viewer</PackageProjectUrl>
		<RepositoryUrl>https://github.com/porohkun/Markdig.Wpf.Viewer</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>markdown;wpf;markdig</PackageTags>

		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Markdig" Version="1.1.3" />
	</ItemGroup>

</Project>
